### ISSUE TITLE
Improve Rust Documentation for EVM

### ISSUE THREAD

**Issue by pgebheim** [0xPolygonZero/plonky2#1376]
## Goal

Create high-level rust documentation that encompasses the API for the zk-evm implementation.

## Tasks

Priority:
- [ ] Add module level documentation to evm/src/lib.rs - High level overview of how to use the evm proving system, link to sub-documentation for interfaces, data structures, and main interface. This content should be able to be used in the main evm README. [Check out this example from Paladin](https://github.com/0xPolygonZero/paladin/blob/main/paladin-core/src/lib.rs)
- [ ] Document prover.rs - Code examples of how major API entrypoints. [Example from Paladin](https://github.com/0xPolygonZero/paladin/blob/b2f04f0ef5112035f4e6a044aaad7c494bfe99e7/paladin-core/src/runtime/mod.rs#L218).
- [ ] Document the major types used within prover.rs during proof generation

Goal:
- [ ] Add documentation with example across the board for all public APIs (modules in the evm/src). Examples should represent test-cases such that examples in the documentation is actionable.

**Comment by Nashtare** [comment]
@pgebheim does the linked PR satisfy what you had in mind? I'll let you close this or clarify if you want more specific doc
