### ISSUE TITLE
Reducing proof size

### ISSUE THREAD

**Issue by wborgeaud** [0xPolygonZero/plonky2#202]
- [x] Compress Merkle paths. **Done in #255**.
- [x] Remove the element that can be inferred in the FRI reduction step. We already did that before f2c423e, but it was removed when we replaced the `InsertionGate` with the `RandomAccessGate`. We can add it back to save some field elements. **Done in #298**.
- [x] Replace Merkle caps with Merkle roots in the compressed proofs. In #170 we replace Merkle roots with Merkle caps to save some gates in the recursive verifier. However this is a bit wasteful in compressed proofs, so replacing the caps with the roots would save some space there.
- [x] The FRI verifier queries the oracle at many indices that are not necessarily distinct. We could check for duplicates and remove the duplicate query proofs in the compressed proofs. **Done in #279**.
- [x] We could implement our own proof serialization. Right now `serde_cbor` wastes quite a bit of space. For example a vector of 100 `CrandallField` elements is serialized with 902 bytes, whereas a simple byte array would take 800 bytes. **Done in #280**.
- [x] Reduce `num_query_rounds`. The proof size is currently given by `12.4 + 6.7*num_query_rounds` KB, so simply reducing `num_query_round` can save quite a bit of memory. Note that we'd need to increase `proof_of_work_bits` or `rate_bits` to maintain security, which would in turn increase the proving time.
